select-java: avoid exec multiple paths
both `dpkg -L .. | grep '/java$'` and `rpm -ql .. | grep '/java$`
can return multiple matches. and before this change, we just exec
the returned string even if it could include multiple paths.

after this change, when selecting java for debian and ubuntu,
use the path of `/usr/lib/jvm/java-11-openjdk-${arch}/bin/java` instead.
when selecting java for fedora and centos, we just return the first
path of `/usr/lib/jvm/jre-${version}-openjdk/bin/java` which exists.

this should address the failure like

```
Error: Could not find or load main class .usr.lib.jvm.java-8-openjdk-arm64.bin.java
```
when launching scylla-jmx as a service on a ubuntu box where
openjdk-8-jre-headless is installed, because:

```
$ dpkg -L openjdk-8-jre-headless | grep '/java$'
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
/usr/lib/jvm/java-8-openjdk-amd64/bin/java
```
so the second line would be considered as the command line argument
pass to the first line.

Fixes #206
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>